name: snyk-sca-scan-python-code
kind: workflow
apiVersion: automation.cloudbees.io/v1alpha1
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  snyk-sast-scan:
    steps:
      - name: checkout assert
        uses: cloudbees-io/checkout@v1
      - name: snyk sast
        uses: cloudbees-io/snyk-sca-plugin-private@v1
        with:
          org-id: ${{ vars.SNYK_ORG_NAME }}
          token: ${{ secrets.SNYK_TOKEN }}
